#ifndef CREEDCORTEX_HPP
#define CREEDCORTEX_HPP
#include <CreedAccuracy.hpp>
#include <CreedActivations.hpp>
#include <CreedCore.hpp>
#include <CreedCrossEntropy.hpp>
#include <CreedDense.hpp>
#include <CreedGlorot.hpp>
#include <CreedLayer.hpp>
#include <CreedLoss.hpp>
#include <CreedMetric.hpp>
#include <CreedMNIST.hpp>
#include <CreedMSE.hpp>
#include <CreedOptimizer.hpp> 
#include <CreedSequential.hpp>
#include <CreedSGD.hpp>
#include <CreedSGDMomentum.hpp>
#include <CreedSimpleDerivative.hpp>
#include <CreedStandardDistribution.hpp>
#include <CreedWeightInitializer.hpp>
#endif